/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stickynotes;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Swanm Htet Lynn
 */
public class AddNoteForm extends javax.swing.JFrame {

    private ConnectDbMng cdb = new ConnectDbMng();
    private DateTimeMng dtmng = new DateTimeMng();
    private ArrayList<Notes> alNotes = cdb.getAllNotes();
    private ArrayList<Notes> notesInCategory;
    private String pref;
    private Categories cate;
    
    public AddNoteForm(Categories category, String preFrame) {
        cate = category;
        pref = preFrame;
        initComponents();
        centerFrameOnScreen();
        cate_cbo.removeAllItems();
        setSize(642, 424);
        if (category!=null) {
            cate_cbo.addItem(category.getCateName());
        }
        else {
            ArrayList<Categories> category_al = cdb.getAllCategories();
                for (Categories cateObj : category_al) {
                    String cate_name = cateObj.getCateName();
                    cate_cbo.addItem(cate_name);
                }
        }

    }
    
    private void clickBackBtn(Categories cate, String preFrame){
        if( "CUI".equals(preFrame)){
            CategoryUI cui = new CategoryUI(new ConnectDbMng().getAllCategories());
            cui.setTitle("Sticky Notes");
            cui.setVisible(true);
            cui.setDefaultCloseOperation(3);
        }
        else{
            StickyNotesUI sui = new StickyNotesUI(cate);
            sui.setTitle("Sticky Notes");
            sui.setVisible(true);
            sui.setDefaultCloseOperation(3);
        }
        dispose();
    }
    
    private void centerFrameOnScreen() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;
        int frameWidth = getWidth();
        int frameHeight = getHeight();
        int x = (screenWidth - frameWidth) / 2;
        int y = (screenHeight - frameHeight) / 2;
        setLocation(x, y);
        setResizable(false);
    }
     private boolean duplicate_exist(Notes note){
        for (Notes item : notesInCategory){
            if (item.getTitle().equals(note.getTitle())) {
                return true;
            }
        }
        return false;
    }
    private boolean duplicate_exist(String title_name){
        for (Notes item : notesInCategory){
            if (item.getTitle().equals(title_name)) {
                return true;
            }
        }
        return false;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        title_label = new javax.swing.JLabel();
        title_tb = new javax.swing.JTextField();
        title_label1 = new javax.swing.JLabel();
        mark_as_sticky = new javax.swing.JCheckBox();
        cate_cbo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        content_ta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sticky Notes");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(642, 424));
        setResizable(false);

        btnsave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Category :");

        btncancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btncancel.setText("CANCEL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        title_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_label.setText("Title :");

        title_tb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title_tbActionPerformed(evt);
            }
        });

        title_label1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_label1.setText("Add Some Details :");

        mark_as_sticky.setText("Mark as Sticky");
        mark_as_sticky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark_as_stickyActionPerformed(evt);
            }
        });

        cate_cbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cate_cbo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cate_cboItemStateChanged(evt);
            }
        });
        cate_cbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cate_cboActionPerformed(evt);
            }
        });

        content_ta.setColumns(20);
        content_ta.setRows(5);
        jScrollPane1.setViewportView(content_ta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mark_as_sticky)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(title_label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(title_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1)
                                .addComponent(title_tb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cate_cbo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cate_cbo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mark_as_sticky)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        String title = title_tb.getText();
        String content = content_ta.getText();
        String category = cate_cbo.getSelectedItem().toString();
        notesInCategory = cdb.getNotesInCategory(category);
        if (!"".equals(title) && !"".equals(content) && duplicate_exist(title)==false) {
            if (title.length()>32 || content.length()>128) {
                JOptionPane.showMessageDialog(null, "Only 32 characters are allowed for Title and 128 characters are allowed as content.");
            }
            else{
                String current_date = dtmng.getFormattedCurrentDate();
                boolean completed = false;
                boolean sticky = mark_as_sticky.isSelected();
                cdb.insertToNoteTable(title, content, current_date
                    , completed,sticky , category);
                JOptionPane.showMessageDialog(null, "A sticky note is saved successfully.");
                StickyNotesUI sui = new StickyNotesUI(cdb.getCategoryformCateName(category));
                sui.setTitle("Sticky Notes");
                sui.setVisible(true);
                dispose();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Error adding stickynote, Please try again.");
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        clickBackBtn(cate, pref);
    }//GEN-LAST:event_btncancelActionPerformed

    private void mark_as_stickyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark_as_stickyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark_as_stickyActionPerformed

    private void cate_cboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cate_cboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cate_cboActionPerformed

    private void title_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title_tbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_title_tbActionPerformed

    private void cate_cboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cate_cboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cate_cboItemStateChanged

//      public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cate_cbo;
    private javax.swing.JTextArea content_ta;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mark_as_sticky;
    private javax.swing.JLabel title_label;
    private javax.swing.JLabel title_label1;
    private javax.swing.JTextField title_tb;
    // End of variables declaration//GEN-END:variables
}
